#Login page elements
txt_loginUserName="name:userName"
txt_loginpassword="name:password"
btn_sigin="xpath://input[@name='submit']"

#Register page elements
link_Reg= "xpath://a[normalize-space()='REGISTER']"
txt_firstName="name:firstName"
txt_lastName="name:lastName"
txt_phone="name:phone"
txt_email="name:userName"
txt_add1="name:address1"
#txt_add2="name:address2"
txt_city="name:city"
txt_state="name:state"
txt_postCode="name:postalCode"
drp_country="name:country"
txt_userName="name:email"
txt_Password="xpath://input[@name='password']"
txt_confirmpwd="xpath://input[@name='confirmPassword']"
btn_submit="xpath://input[@name='submit']"